#!/usr/bin/env bun
// The model's side of a board task on cookbooks/notes-api, printed as the openai twin's scenario. The shape
// is the todo-cli scenario's (one item per fire, a worker and a reviewer, stateless rules keyed on the
// conversation's own text) with this cookbook's own items and stages; the two share no code beyond the runner.
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const here = import.meta.dir;
const roadmap = readFileSync(resolve(here, '../../../cookbooks/notes-api/ROADMAP.yml'), 'utf8');
const items = [...roadmap.matchAll(/- id: ([a-z0-9-]+)\n(?:(?!- id:)[\s\S])*?title: (.+)/g)].map((m) => ({ id: m[1]!, title: m[2]!.trim() }));

function files(dir: string, base = dir): string[] {
  return readdirSync(dir).flatMap((n) => { const p = join(dir, n); return statSync(p).isDirectory() ? files(p, base) : [relative(base, p)]; });
}
// The roadmap as the model rewrites it for one item: every item up to and including this one is done.
function roadmapAfter(itemId: string): string {
  const upTo = items.findIndex((i) => i.id === itemId);
  let out = roadmap;
  for (const item of items.slice(0, upTo + 1)) out = out.replace(new RegExp(`(- id: ${item.id}\\n(?:(?!- id:)[\\s\\S])*?status: )planned`), '$1done');
  return out;
}
// The command the model runs to implement one item: the stage's files written cumulatively, the check,
// the commit as the agent, the push. Outcome markers are assembled so an echoed command never reads as one.
function implement(item: { id: string; title: string }): string {
  const stage = resolve(here, 'stages', item.id);
  const heredoc = (path: string, text: string) => `cat > '${path}' <<'__OA_FILE__'\n${text}${text.endsWith('\n') ? '' : '\n'}__OA_FILE__`;
  const writes = [...files(stage).map((f) => heredoc(f, readFileSync(join(stage, f), 'utf8'))), heredoc('ROADMAP.yml', roadmapAfter(item.id))].join('\n');
  return [
    `git fetch -q origin main && git checkout -q -B agent/${item.id} origin/main || { echo "IMPLEMENTATION_""RAN cannot start"; exit 1; }`,
    writes,
    `bun run check >/dev/null 2>&1 || { echo "IMPLEMENTATION_""RAN the check failed:"; bun run check 2>&1 | tail -20; exit 1; }`,
    `git add -A && git -c user.name='Open Autonomy agent' -c user.email='agent@open-autonomy.org' commit -q -s -m '${item.id}: ${item.title.replace(/'/g, "'\\''")}' && git push -q -u origin agent/${item.id} || { echo "IMPLEMENTATION_""RAN push failed"; exit 1; }`,
    `echo "IMPLEMENTATION_""RAN PUSHED_BRANCH""=agent/${item.id} $(git rev-parse --short HEAD)"`,
  ].join('\n');
}

const handlers = [
  { id: 'clamped-output-cap', on: { maxTokensBelow: 16384 }, respond: { text: '', finishReason: 'length' } },
  { id: 'probe', on: { anyTextIncludes: 'probe:' }, respond: { text: 'ok' } },
  // Answers to a tool result come first: the text that triggered the call is still in the conversation.
  { id: 'worker-handed-off', on: { toolResultFor: 'kanban_request_review' }, respond: { text: 'Handed off to review: the agent branch is pushed, the landing workflow merges it when the checks pass.' } },
  { id: 'worker-stopped', on: { toolResultFor: 'kanban_block' }, respond: { text: 'Stopped: the implementation ran but did not push. Nothing was recorded on the roadmap.' } },
  { id: 'reviewer-done', on: { toolResultFor: 'kanban_complete' }, respond: { text: 'Approved.' } },
  ...items.map((item) => ({ id: `handoff-${item.id}`, on: { anyTextIncludes: `PUSHED_BRANCH=agent/${item.id}`, hasTool: 'kanban_request_review' }, respond: { toolCalls: { name: 'kanban_request_review', arguments: { summary: `HANDOFF pushed agent/${item.id}: ${item.title} with its test, the check starts the server and passes, status done in ROADMAP.yml; the landing workflow merges the branch.` } } } })),
  { id: 'worker-blocked', on: { anyTextIncludes: 'IMPLEMENTATION_RAN', hasTool: 'kanban_block' }, respond: { toolCalls: { name: 'kanban_block', arguments: { reason: 'the implementation ran but did not push; its output is on the thread', kind: 'transient' } } } },
  { id: 'reviewer-verdict', on: { toolResultFor: 'kanban_show', anyTextIncludes: 'HANDOFF pushed agent/' }, respond: { toolCalls: { name: 'kanban_complete', arguments: { summary: 'Approved: the handoff names the pushed agent branch and its commit, ROADMAP.yml carries the item as done on it, and the landing workflow merges it when the checks pass.' } } } },
  ...items.map((item) => ({ id: `implement-${item.id}`, on: { toolResultFor: 'kanban_show', anyTextIncludes: `ROADMAP_ITEM=${item.id}` }, respond: { toolCalls: { name: 'terminal', arguments: { command: implement(item) } } } })),
  { id: 'orient', on: { userTextIncludes: 'work kanban task', lastMessageIsToolResult: false }, respond: { toolCalls: { name: 'kanban_show', arguments: {} } } },
  { id: 'housekeeping', on: {}, respond: { text: 'ok' } },
];
process.stdout.write(`${JSON.stringify({ $comment: 'Generated by world/handlers/notes-api/gateway.ts — edit that and the stages, not this.', handlers }, null, 2)}\n`);
