#!/usr/bin/env bun
// The scripted model the platform's gateway (the Merge twin) answers: the turns of the profiles that run on Claude Code
// through the install's own route (the org valve, the platform, Merge), so their calls are metered on the organization's
// key (RFC 0021 decision 7). They are scenario.ts's turns, in Claude Code's tool (`Bash`, `command`); the Codex profiles'
// turns stay with the OpenAI twin (the owner's subscription route, unmetered as in production).
const CLAUDE_TURNS = new Set(['after-command', 'card-reviewer', 'card-coder', 'card-reviewer-native', 'card-coder-native', 'manager-tick', 'reviewer-verdict', 'coder-review-demo', 'am-digest', 'housekeeping']);
const scripted = Bun.spawnSync({ cmd: ['bun', `${import.meta.dir}/scenario.ts`], env: process.env, stdout: 'pipe', stderr: 'inherit' });
if (scripted.exitCode !== 0) throw new Error('model/scenario.ts failed');
const { handlers } = JSON.parse(scripted.stdout.toString()) as { handlers: Array<{ id: string; on: unknown; respond: { text?: string; toolCalls?: { name: string; arguments: { cmd: string } } } }> };
const claude = handlers.filter((h) => CLAUDE_TURNS.has(h.id)).map((h) => h.respond.toolCalls
  ? { ...h, respond: { toolCalls: { name: 'Bash', arguments: { command: h.respond.toolCalls.arguments.cmd, description: h.id } } } }
  : h);
console.log(JSON.stringify({ $comment: 'GENERATED by world/model/merge.ts', handlers: claude }, null, 2));
