#!/usr/bin/env bun
// The scripted model the voice front's realtime provider (OpenAI's P3 pack, its /v1/realtime socket) answers in the
// account Room's call (RFC 0020 row 24, decision 21): the owner's substantial question is passed to the call's thread
// session (the voice's `delegate`), its acceptance acknowledged once; the session's answer, which the voice runtime
// hands back as an announcement, is spoken. Every other line is the pack's labeled stub.
const handlers = [
  // The session's answer, handed back by the voice runtime as an out-of-band announcement (its instructions carry it).
  {
    id: 'call-announce',
    on: { anyTextIncludes: "speaking your coding session's answer" },
    respond: { text: "We landed on CSV first, then the API. It is recorded as this thread's first answer." },
  },
  {
    id: 'call-delegate',
    on: { userTextIncludes: 'where did we land on the export design', lastMessageIsToolResult: false },
    respond: { toolCalls: { name: 'delegate', arguments: { task: 'The owner asks on the call where we landed on the export design. Give the decision and the message it was recorded from.' } } },
  },
  {
    id: 'call-delegated',
    on: { lastMessageIsToolResult: true },
    respond: { text: 'Let me check with the session holding this call.' },
  },
];
console.log(JSON.stringify({ $comment: 'GENERATED by world/model/realtime.ts', handlers }, null, 2));
