#!/usr/bin/env bun
// The backend copy as a world service: the REAL worker (`@open-autonomy/backend`, the self-host deployment's own entry,
// or a checkout named by OPEN_AUTONOMY_ROOT) under `wrangler dev`, its upstreams the twins the world injected — the
// model rail on the model twin, GitHub on the GitHub twin. The worker takes those as ordinary configuration; nothing in
// it knows it is in a world. The world gives PORT and --persist-to (the books).
import { execFileSync, spawn } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ACCOUNT, CONFIG, GENERATED, MODEL, ROOT, need } from './lib.ts';

const arg = (name: string): string | undefined => { const i = process.argv.indexOf(name); return i >= 0 ? process.argv[i + 1] : undefined; };
const port = need('PORT');
const persist = arg('--persist-to') ?? resolve(GENERATED, 'platform-state');
// Every bound model priced like a flash-class model, so a run reserves against a small ceiling and not the
// unlisted-model ceiling (which would refuse a second call in flight on a small balance).
const prices = Object.fromEntries([...new Set([MODEL, ...CONFIG.models])].map((m) => [m, { input_usd_per_mtok: 0.5, output_usd_per_mtok: 1.5 }]));
const vars: Record<string, string> = {
  MODEL_GATEWAY_URL: need('GATEWAY_TWIN_URL'),
  MODEL_GATEWAY_API_KEY: process.env.MODEL_GATEWAY_API_KEY ?? 'world-gateway-key',
  AGENT_PROXY_ADMIN_TOKEN: process.env.AGENT_PROXY_ADMIN_TOKEN ?? 'world-admin',
  AGENT_PROXY_HMAC_SECRET: process.env.AGENT_PROXY_HMAC_SECRET ?? 'world-hmac-secret',
  GITHUB_API_BASE: need('GITHUB_TWIN_URL'),
  GITHUB_RAW_BASE: 'http://127.0.0.1:9/raw', // dead on purpose: the docs sync falls back to the twin's contents API
  GITHUB_OAUTH_BASE: need('GITHUB_TWIN_URL'),
  GITHUB_OAUTH_CLIENT_ID: 'world-open-autonomy',
  GITHUB_OAUTH_CLIENT_SECRET: 'world-oauth-secret',
  GIVE_SESSION_HMAC_SECRET: 'world-give-session-secret',
  GITHUB_TOKEN: 'world-bot',
  DEPLOY_COMMIT: (() => { try { return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim(); } catch { return 'rehearsal'; } })(),
  MODEL_PRICES_JSON: JSON.stringify(prices),
  MAX_GLOBAL_DAILY_USD_CENTS: '20000',
  DEFAULT_FUNDING_ACCOUNT: ACCOUNT,
};
// The worker's entry: the self-host deployment's, verbatim, on the published package — or on a checkout of the
// backend when one is named (developing the backend against this project).
mkdirSync(GENERATED, { recursive: true });
const checkout = process.env.OPEN_AUTONOMY_ROOT ? resolve(process.env.OPEN_AUTONOMY_ROOT) : undefined;
const backend = checkout && existsSync(resolve(checkout, 'packages/backend/src/index.ts')) ? resolve(checkout, 'packages/backend/src/index.ts') : '@open-autonomy/backend';
if (backend === '@open-autonomy/backend' && !existsSync(resolve(ROOT, '.open-autonomy', 'node_modules', '@open-autonomy', 'backend'))) { console.error('platform: @open-autonomy/backend is not installed beside the reporter (bun install in .open-autonomy), and OPEN_AUTONOMY_ROOT names no checkout'); process.exit(2); }
const entry = resolve(GENERATED, 'platform-entry.ts');
writeFileSync(entry, `// Generated by the rehearsal: the self-host deployment's entry on ${backend}.\nimport { LimitLedger, worker } from ${JSON.stringify(backend)};\nexport { LimitLedger };\nexport default worker();\n`);
const toml = resolve(GENERATED, 'platform.wrangler.toml');
writeFileSync(toml, `name = "rehearsal-backend"\nmain = ${JSON.stringify(entry)}\ncompatibility_date = "2026-06-15"\nworkers_dev = false\n\n[vars]\nMAX_BODY_BYTES = "1048576"\n\n[triggers]\ncrons = ["0 6 * * *"]\n\n[[durable_objects.bindings]]\nname = "LIMITS"\nclass_name = "LimitLedger"\n\n[[migrations]]\ntag = "v1"\nnew_sqlite_classes = ["LimitLedger"]\n`);
const inspector = await (async () => { const s = Bun.serve({ port: 0, fetch: () => new Response('') }); const p = s.port; s.stop(true); return p; })();
const args = ['wrangler', 'dev', '-c', toml, '--port', port, '--inspector-port', String(inspector), '--ip', '127.0.0.1', '--persist-to', persist, '--show-interactive-dev-session', 'false'];
for (const [k, v] of Object.entries(vars)) args.push('--var', `${k}:${v}`);
// Supervised the way a deployment supervises its worker: wrangler's dev proxy is known to drop under a long
// session, and the world's health check would otherwise read that as the platform gone.
// A wrangler whose dev proxy died can leave its workerd holding the port; the restart reclaims it first, or every
// restart dies on the bind and the world's readiness probe runs out.
const reclaim = (): void => {
  for (let i = 0; i < 25; i++) {
    let holders: string[] = [];
    try { holders = execFileSync('lsof', ['-ti', `tcp:${port}`, '-sTCP:LISTEN'], { encoding: 'utf8' }).split('\n').filter(Boolean); } catch { /* nobody listens */ }
    if (!holders.length) return;
    for (const pid of holders) { try { process.kill(Number(pid), 'SIGKILL'); } catch { /* gone */ } }
    Bun.sleepSync(200);
  }
};
const cwd = resolve(ROOT, '.open-autonomy');
const launch = () => spawn('bunx', args, { cwd, stdio: 'inherit', env: { ...process.env, WRANGLER_SEND_METRICS: 'false' } });
let child = launch();
let stopping = false;
const restart = (code: number | null) => { if (stopping) return; console.error(`rehearsal/platform.ts: wrangler dev exited (${code}); restarting on :${port}`); reclaim(); child = launch(); child.on('exit', restart); };
child.on('exit', restart);
for (const sig of ['SIGTERM', 'SIGINT'] as const) process.on(sig, () => { stopping = true; child.kill(sig); process.exit(0); });
