#!/usr/bin/env bun
// The scripted brain: what the model twin answers when the brain thinks, printed as the scenario document the twin
// serves (the kit's rehearsal writes it into the world). Handlers are ordered and first-match; each keys on the
// conversation's own text — the wake's token, the last tool's result — never on call counts. Judgment the real model
// makes in prose is fixed here; what the rehearsal proves is the plumbing around it.
//
// The starter scripts one turn: the PM job's wake (`WAKE: PM`, the token its prompt carries and the skill text never
// does) runs rehearsal/model/pm-beat.ts as the model's terminal call, and the beat's last line is the verdict. Add a
// handler per wake the project has; the misses the twin ledgers (`volter-world tail`) name the ones still unwritten.
const beat = 'rehearsal/model/pm-beat.ts'; // relative to the brain's checkout, where its terminal starts
const handlers = [
  { id: 'pm-done', on: { userTextIncludes: 'WAKE: PM', toolResultFor: 'terminal', anyTextIncludes: 'PM_BEAT_DONE' },
    respond: { text: 'Scrum done: the sourced roadmap reconciled with what arrived, the plan landed, the inputs acknowledged.' } },
  { id: 'pm-error', on: { userTextIncludes: 'WAKE: PM', toolResultFor: 'terminal' },
    respond: { text: 'Scrum did not finish: the beat failed; its error is in the terminal result. The planning worktree is preserved for the next run.' } },
  { id: 'pm-act', on: { userTextIncludes: 'WAKE: PM', lastMessageIsToolResult: false },
    respond: { toolCalls: { name: 'terminal', arguments: { command: `bun ${beat}` } } } },
];
console.log(JSON.stringify({ $comment: 'GENERATED by rehearsal/model/scenario.ts — the scripted brain for the model twin; edit the generator.', extractors: {}, handlers }));
